### PR TITLE
Indicate charging state only if device supports multi color led

### LINKED ISSUE #1336: Below-screen button blinking when screen off and device charging even if there are no notifications
- Device: Meizu MX4 arale
- Channel: devel
- Build: 2020-01-04

### Steps to reproduce
Make sure there are no unread notifications left and turn the screen off. The button below screen starts blinking.

### Expected behavior
That behaviour (blinking button) should only appear if there are unread notifications present.

### Actual behavior
Button is blinking no matter what.

This behaviour is observable on devel for at least the last ~2 or 3 weeks.

### PR DESCRIPTION
**Pull request by wdehoog**
Fixes https://github.com/ubports/ubuntu-touch/issues/1336

### CODE REVIEW

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This causes an error during testing:

```
file:///build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpdsc/tests/qmltests/Tutorial/tst_Tutorial.qml:142:17: Type Shell unavailable 
                     Shell { 
                     ^
file:///build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpdsc/qml/Shell.qml:512:9: Type Panel unavailable 
             Panel { 
             ^
file:///build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpdsc/qml/Panel/Panel.qml:438:5: Type IndicatorsLight unavailable 
         IndicatorsLight { 
         ^
file:///build/varlibjenkinsworkspaceubportsunityPRunityubportsgbpdsc/qml/Panel/Indicators/IndicatorsLight.qml:46:40: DeviceConfiguration is not a type 
         property var _deviceConfiguration: DeviceConfiguration { 
                                            ^
```

It appears that the appropriate component is not imported in IndicatorsLight.qml.

**Comment by UniversalSuperBox** [comment]
I noticed that the tests for the DeviceConfigParser module were not being run, so I fixed that up with https://github.com/ubports/unity8/pull/291. After that is merged, I'll let you know. At that time you can run `git pull --rebase upstream xenial` on this branch (assuming you have `https://github.com/ubports/unity8` as the `upstream` remote) to integrate those changes. Then you can add the attached patch using `git apply < deviceconfigparserpatch.txt` to get unit tests for these changes.

[deviceconfigparserpatch.txt](https://github.com/ubports/unity8/files/4309586/deviceconfigparserpatch.txt)

Hit me up in Telegram for more information. :D

**Comment by UniversalSuperBox** [comment]
#291 has been merged.

**Comment by UniversalSuperBox** [comment]
Finally circling back to this (sorry)...

I think I was wrong about removing the `turbo` config from the qml file. I cannot find any INI file in the device's image.

Additionally, `arale`, the MX4, has the same white-only LED in its home button. Its config is in the qml file, so it can also be adjusted there.

Again, sorry, I hate to steer you wrong.

**Comment by UniversalSuperBox** [comment]
We have a successful test of this on a Pro 5, quieting down that blinking light

**Comment by zubozrout** [comment]
If only installing PR's was easy on MX4, but with no space left on the root FS that's always a no go. So here is a workaround I've used to test this for those interested:

```
sudo ubports-qa install PR-287 # will fail with No space left on device error on apt update command aready
sudo apt -o Dir::Cache::Archives=/home/phablet update # but the above changes are kept so we can do this now
sudo apt -o Dir::Cache::Archives=/home/phablet upgrade # and upgrade
```

Anyway, it seems to work. No more blinking button when charging unless I receive a notification which is as it was before and expected. Awesome, thank you :).

**Review by UniversalSuperBox — APPROVED** [review]
Tests good! Let's do it.

**Pull request merged**
