### PR TITLE
A new README.md file

### PR DESCRIPTION
**Pull request by ismaelbonato**
First version. 

Please can you verify if I made a mistake?

### CODE REVIEW

**Comment by NeoTheThird** [comment]
@mariogrip Is the CI server broken or something?

**Comment by mariogrip** [comment]
@NeoTheThird should not be, will check it out. but merged for now

**Comment by NeoTheThird** [comment]
nvm

**Comment by NeoTheThird** [comment]
c641fb8dde6d33a00e154f74a3fc71d743eb9ff7

**Pull request merged**
