### PR TITLE
YUMI-7: Make app drawer check if appid exists in the model

### PR DESCRIPTION
**Pull request by maciek134**
This makes sure that no duplicate apps will ever appear in the drawer.

This file could use with a bit of cleanup, but I'm hoping to still fit this into OTA-25.

### CODE REVIEW

**Comment by maciek134** [comment]
```
Segmentation fault
tests/qmltests/CMakeFiles/xvfbtestGreeterView.dir/build.make:60: recipe for target 'tests/qmltests/CMakeFiles/xvfbtestGreeterView' failed
```
Yay

**Comment by maciek134** [comment]
```
FAIL!  : qmltestrunner::VideoMediaServices::test_fullscreenSwitch() Should have switched to fullscreen mode.
   Actual   (): false
   Expected (): true
   Loc: [/build/unity8-8.20+ubports+0~20230327062908.4~1.gbpd0dfe1/tests/qmltests/Components/tst_MediaServices.qml(170)]
```
It keeps failing on either this one on armhf or the segfault on aarch64

**Comment by JamiKettunen** [comment]
As per @Flohack74's comment on https://ubports.atlassian.net/browse/YUMI-7 it's already too late for xenial now, please create an MR against https://gitlab.com/ubports/development/core/lomiri and let's continue any further efforts on 20.04 :)

**Comment by maciek134** [comment]
Yup, closing, bye Xenial :)

Btw I guess this repo can be archived now

**Pull request closed without merging**
