### PR TITLE
qml: Fix Drawer hiding away under the user

### PR DESCRIPTION
**Pull request by fredldotme**
- preventHiding when launcher is in various launcher states

### CODE REVIEW

**Comment by kugiigi** [comment]
Not sure if this could be a help but here is my 3am fix :smile: 
I had a different approach. Basically, I found out that the property `autohideEnabled` isn't reset so the launcher/drawer just closes automatically every time after it was opened via pushing the mouse to the left edge at least once.

I wonder if we should also have temporary visible state for the drawer so it will also close once the mouse is out of its area.

**Review by Flohack74 — APPROVED** [review]

**Comment by luksus42** [comment]
Not sure, if its connected with this change, but the app drawer is not opening anymore when touching the ubuntu icon in staged mode.

**Comment by Flohack74** [comment]
@fredldotme can you check that last comment?

**Comment by luksus42** [comment]
FYI: I did an update this morning (dev), only 1.2MB update size, and now the Button is working again. So maybe it is already fixed or it was just some device specific issue on my FP3.

**Pull request merged**
