### PR TITLE
Allow user setting "autohideLauncher" to set prefrence

### PR DESCRIPTION
**Pull request by mateosalta**
Check if user has set autohideLauncher for locked launcher preference.

### CODE REVIEW

**Comment by mateosalta** [comment]
fix https://github.com/ubports/unity8/issues/282

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This patch appears to put off the problem, not fix it. When a user wants to auto-hide the launcher on the desktop, they do not necessarily want it to always auto-hide on mobile.

It's very likely that this will fail tests. Even if it does not, the tests will need to be modified to ensure that every combination of auto-hide or not, phone, tablet, or desktop is covered. See https://github.com/ubports/unity8/blob/xenial/tests/qmltests/tst_Shell.qml#L3243 for this test.

**Comment by dobey** [comment]
As @UniversalSuperBox said, this doesn't actually provide what you are thinking it does. Instead it complicates the meaning of the setting (meaning, you must set it to always, but then the launcher isn't always on). I don't think it's a reasonable compromise either, for the complaint you've put forward, as the setting should already be set to this by default, which means all you're doing is restoring the previous behavior for everyone by default.

**Comment by mateosalta** [comment]
> As @UniversalSuperBox said, this doesn't actually provide what you are thinking it does. Instead it complicates the meaning of the setting (meaning, you must set it to always, but then the launcher isn't always on). I don't think it's a reasonable compromise either, for the complaint you've put forward, as the setting should already be set to this by default, which means all you're doing is restoring the previous behavior for everyone by default.

Ah, that would be a deal breaker for sure. I thought autohide was off by default...

**Comment by Fuseteam** [comment]
I'm somehow two years late on this idea.... 

> It complicates the meaning of the setting (meaning, you must set it to always, but then the launcher isn't always on). 

@dobey isn't this currently the case? The default setting for the launcher is "always hide", but it is never hidden on phones and tabets(?). Wouldn't it be better to set the default setting to "always shown" and have the user set "always hide" across staged and desktop mode?

**Pull request closed without merging**
