### PR TITLE
Files and Folders are shown on git status

### PR DESCRIPTION
**Pull request by ismaelbonato**
Remove Files and Folders from git status when I Run unity 8 on my desktop without installing and using Kdevelop4

### CODE REVIEW

**Review by mardy — APPROVED** [review]
Looks good, thanks!

**Comment by NeoTheThird** [comment]
(not that i don't trust your judgment @mardy :D, i'd just like @mariogrip's two cents on if this is targeting the correct branch and how we want to go about keeping the branches in sync)

@ismaelbonato Awesome, thank you!

**Comment by mardy** [comment]
@NeoTheThird Indeed, whenever I review any submissions I'm paying far more attention to the changes, than to the target branch. So you are right in not hurrying up to merge things :-)

**Comment by ismaelbonato** [comment]
Which branch would be better to do Pull request? This branch is the only I can work properly on my rig for now. But with this initials changes I think it can be applied on the main branch if you want.

**Comment by mariogrip** [comment]
@ismaelbonato Using xenial_-_mir26 or bionic is fine, we will try to keep these two in sync

**Pull request merged**
