### PR TITLE
Check if search word contains, not just startsWith

### PR DESCRIPTION
**Pull request by mariogrip**
This fixes: https://github.com/ubports/ubuntu-touch/issues/1122

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Installed with `ubports-qa`, does not seem to fix the usecase described in https://github.com/ubports/ubuntu-touch/issues/1122. Did you test this on-device with a non-system app?

**Comment by mariogrip** [comment]
> Installed with `ubports-qa`, does not seem to fix the usecase described in [ubports/ubuntu-touch#1122](https://github.com/ubports/ubuntu-touch/issues/1122). Did you test this on-device with a non-system app?

humm, can you check that the version matches `8.20+ubports+0~20190923005745.1~1.gbpdc852a` I have notice that ubports-qa does not install due to the edge pin we added.

**Comment by NeoTheThird** [comment]
Ah, that would have been good to know :D Yep, version does not match. Can try later.

**Review by dobey — APPROVED** [review]

**Review by UniversalSuperBox — APPROVED** [review]
All good here! Wonder why it was done the other way.

**Comment by NeoTheThird** [comment]
Seems to work

**Pull request merged**
