### PR TITLE
Fix Qt >= 5.9

### LINKED ISSUE #45: Unity.Test broken with Qt5.9
See https://github.com/ubports/unity8/blob/bionic/tests/utils/CMakeLists.txt#L1
Error:
```
/src/unity8/tests/utils/modules/Unity/Test/TouchEventSequenceWrapper.cpp:37:13: error: ‘class QQuickWindowPrivate’ has no member named ‘flushDelayedTouchEvent’; did you mean ‘deliverDelayedTouchEvent’?
         wp->flushDelayedTouchEvent();
             ^~~~~~~~~~~~~~~~~~~~~~
             deliverDelayedTouchEvent
```

### PR DESCRIPTION
**Pull request by vanyasem**
Closes #45

### CODE REVIEW

**Comment by vanyasem** [comment]
Decided to extend the PR even more by fixing similar issues from https://github.com/ubports/unity8/commit/95d8efbee7f6d3c4ef7f1d091f36d64d2155fd80

**Comment by vanyasem** [comment]
The CI failed, but it appears that it's not related to my changes

**Comment by vanyasem** [comment]
Maybe it would be wise to declare a single function, and to just call it. But I don't know how to approach it the right way

**Comment by vanyasem** [comment]
Tested all tests (sorry for saying that), they all passed :P
Arch GNU/Linux, Qt 5.11.1

tst_DragHandle: https://paste.ubuntu.com/p/qMNtFZVcn9/
GestureTest.cpp (tst_TouchGestureArea): https://paste.ubuntu.com/p/qnhZxY55vw/

**Comment by vanyasem** [comment]
Dalton Durst, [09.09.18 19:04]
https://ci.ubports.com/blue/organizations/jenkins/ubports%2Funity8/detail/PR-46/6/pipeline#step-39-log-828

Dalton Durst, [09.09.18 19:04]
These five lines

Dalton Durst, [09.09.18 19:04]
"file" exists but is not installed to anywhere

Dalton Durst, [09.09.18 19:05]
I'm no debhelper expert (that'd be @tsimonq2), but I'd say that something isn't getting cleaned up

**Comment by vanyasem** [comment]
Rodney, [09.09.18 19:13]
It means something is installed by make install, but not removed in debian rules, and not included in any of the binary packages

**Comment by vanyasem** [comment]
Florian Leeber, [09.09.18 19:55]
Remove tests

Rodney, [09.09.18 20:45]
Don't install the files, or include them in a binary package, via the .install file for it

**Comment by tsimonq2** [comment]
```
dh_install -X'*.pyc' --fail-missing
dh_install: Please use dh_missing --list-missing/--fail-missing instead
dh_install: This feature will be removed in compat 12.
dh_missing: usr/lib/x86_64-linux-gnu/unity8/qml/utils/Unity/Test/libUnityTestQml.so exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/unity8/qml/utils/Unity/Test/StageTestCase.qml exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/unity8/qml/utils/Unity/Test/UnityTestCase.qml exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/unity8/qml/utils/Unity/Test/MouseTouchEmulationCheckbox.qml exists in debian/tmp but is not installed to anywhere
dh_missing: usr/lib/x86_64-linux-gnu/unity8/qml/utils/Unity/Test/qmldir exists in debian/tmp but is not installed to anywhere
```
First off, we need to convert all `dh_install` stanzas to `dh_missing`.

These errors come from [this line](https://github.com/ubports/unity8/blob/bionic/debian/rules#L23). You probably need to add the lines to [unity8-private's install file](https://github.com/ubports/unity8/blob/xenial/debian/unity8-private.install) in the same format as shown, or another binary package if similar files are there as well.

**Comment by vanyasem** [comment]
I guess I just need to revert this commit https://github.com/ubports/unity8/commit/a0335d547bb0d348d8b8b50b47ab6a3e770be304

**Comment by vanyasem** [comment]
That fixed it, right

**Comment by vanyasem** [comment]
Florian Leeber, [15.09.18 13:46]
there is no PR-46 on the server, yes

Florian Leeber, [15.09.18 13:46]
is that an old one?

Ivan Semkin, [15.09.18 13:46]
[In reply to Florian Leeber]
So-so

Ivan Semkin, [15.09.18 13:47]
Should i close it and open a new one?

Florian Leeber, [15.09.18 13:47]
they are deleted after some time

Florian Leeber, [15.09.18 13:47]
yes its easier. We cleanup after some 2 o3 months

**Pull request closed without merging**
