### PR TITLE
Enable inverted portrait for Arale

### PR DESCRIPTION
**Pull request by cibersheep**
Tested with Arale latest dev build

### CODE REVIEW

**Comment by mateosalta** [comment]
Rotate everything! :)

**Comment by cibersheep** [comment]
I would agree but I prefer to be a bit conservative and only go by the devices that I can test... so... help testing devices is welcome

**Comment by cibersheep** [comment]
Oh. Could we restart the CI when you have a moment?

**Comment by Flohack74** [comment]
Is this bitrotting here or no longer valid?

**Comment by cibersheep** [comment]
The CI threw an error but now is passed it... weeeeheee... so, you could merge it after I test this again.
Thanks!

**Comment by cibersheep** [comment]
Tested. works as expected :)

**Comment by Flohack74** [comment]
We actually kinda closed already new additons to this cycle for the OTA, is this a critical or major bug?

**Comment by cibersheep** [comment]
Not at all... it's just a really minor fix

**Review by UniversalSuperBox — APPROVED** [review]
CI status is invalid, due to reindexing of the branch the latest job had to be canceled. This PR is valid and will be merged after CI settles.

**Comment by cibersheep** [comment]
Works as expected :)

**Pull request merged**
