### PR TITLE
WIP: greeter Theme changes

### PR DESCRIPTION
**Pull request by mateosalta**
try some theme changes

### CODE REVIEW

**Comment by mateosalta** [comment]
this removes the keyboard background, and changes hardcoded colors into theme colors, unfortunatly this part of lomiri is hardcoded to the dark theme. 

Will have to untangle the mess of specifying different themes in shell elements, then recolor items that we wish to stay a certain color.

**Comment by UniversalSuperBox** [comment]
Are you still working on this @mateosalta?

**Comment by mateosalta** [comment]
yeah, it's an ongoing effort to try and theme the lock-screen: https://forums.ubports.com/topic/6022/login-screen-code-input-design/105

It's getting there, but we went in a new direction, instead of opaque boxes we are going to try and use white elements like the initial lock-screen page with the time and infographics.

**Comment by mateosalta** [comment]
unless I could get it to a intermediate stage, similar to this state: https://forums.ubports.com/assets/uploads/files/1619777417175-screenshot20210430_050857603.png but perhaps a shade on the emergency call as well, and then perform further iterations

- keyboard transparency works
- keep slight transparency on login box for now because of the error text (blocker for having no background box)

**Pull request closed without merging**
