### PR TITLE
 Remove unused link/include to gio and cleanup ashes left from dash and scopes

### PR DESCRIPTION
**Pull request by mariogrip**
Remove unused link/include to gio and cleanup ashes left from dash and scopes

### CODE REVIEW

**Comment by mariogrip** [comment]
oof the dual "build" is getting annoying

**Comment by NeoTheThird** [comment]
> oof the dual "build" is getting annoying

Well, we kind of need to build both. If branch is failing, there's probably something wrong with your pr. If pr is failing, merging would lead the target branch to fail. Kinda important to know both. But we have to do something to make jenkins more reliable and make it easier to see what's going wrong (#182).

**Comment by mariogrip** [comment]
> > oof the dual "build" is getting annoying
> 
> Well, we kind of need to build both. If branch is failing, there's probably something wrong with your pr. If pr is failing, merging would lead the target branch to fail. Kinda important to know both. But we have to do something to make jenkins more reliable and make it easier to see what's going wrong (#182).

Oh wait, this would fix that: https://github.com/ubports/unity8/pull/191 it seems to be due to flaky tests :)

**Comment by mariogrip** [comment]
Ok, rebased. lets see if it builds now :)

**Review by UniversalSuperBox — APPROVED** [review]

**Pull request merged**
