### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by ubports-weblate**
Translations update from [Weblate](https://translate.ubports.com/projects/unity8/unity8/) for Unity8/Unity8.

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
What the heck happened here @Flohack74 @mariogrip ?

**Comment by Flohack74** [comment]
Maybe smth was force-pushed some time ago. Weblate did merge master into its branch, and now all of that is "missing" (I think its identical to master actually, but I wil check)

**Review by Flohack74 — CHANGES_REQUESTED** [review]
Blocked!

**Comment by dobey** [comment]
> Blocked!

Can you fix the ubports-weblate repo? It seems weblate is still pushing translations based on this broken version of the repo.

**Comment by Flohack74** [comment]
Dang yes I should block there and delete this branch...

**Pull request closed without merging**
