### PR TITLE
Made Dash Background's opacity customizable

### PR DESCRIPTION
**Pull request by nfsprodriver**
Needs to be merged with system-settings' PR

### CODE REVIEW

**Comment by mariogrip** [comment]
Thanks for the PR :) but could you target this for the "xenial" branch? since that's where the next ota will be on

**Comment by mariogrip** [comment]
Why did you revert the Jenkinsfile?

**Comment by nfsprodriver** [comment]
Don't know. It appeared when changing the base branch. Jenkins & Co. is your part ;)

**Comment by mariogrip** [comment]
Humm, seems to not touch the jenkins file, so let's merge it and see how it goes

**Pull request merged**
