### PR TITLE
Stage: 'No running apps' hint on top of Spread

### PR DESCRIPTION
**Pull request by fredldotme**
Initial version until I (or someone else) figure out how to animate the hint opacity/visibility with the spread edge gesture.

Concerns bug report https://github.com/ubports/ubuntu-touch/issues/1070

### CODE REVIEW

**Comment by fredldotme** [comment]
CI build failed due to `E: pbuilder-satisfydepends failed.`

**Comment by mariogrip** [comment]
Ok, issue should be fixed now. fixed by: https://github.com/ubports/build-tools/commit/105a02ccc8bfcd60d4b8995bebee58a3f3a8dfd1 

I have triggered a rebuild

**Comment by UniversalSuperBox** [comment]
Here it is in action:

screenshot20190419_114144391

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
