### PR TITLE
provide a default icon for apps (fixes #210)

### LINKED ISSUE #210: default icon for an app
In case of resource load failure, can we provide a default icon as it was the case on Stable ?

### PR DESCRIPTION
**Pull request by lduboeuf**

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
Hmm, I don't think we should copy the image into here, if it's just going to be the same image that's already in the suru theme. Instead we should just use the version from the theme. Also, I think we should change the image so that it doesn't include the Ubuntu logo. It also might be better to solve this issue in the `ubuntu-app-launch` code, which is where icon paths are actually discovered.

**Comment by lduboeuf** [comment]
alright, so better close that PR .

**Comment by lduboeuf** [comment]
so by providing a default icon path in ubuntu-app-launch when anything wrong happens ?

**Comment by lduboeuf** [comment]
https://github.com/ubports/ubuntu-app-launch/blob/xenial/libubuntu-app-launch/application-icon-finder.cpp
here ?

**Comment by dobey** [comment]
Yes. By falling back to the default app icon from the theme, if no icon path is found.

**Comment by lduboeuf** [comment]
> Yes. By falling back to the default app icon from the theme, if no icon path is found.

ok, i see. Well i'm not able to build/test ubuntu-app-launch so can't do it.
With crossbuilder it does not work :-/ like others project.

**Pull request closed without merging**
