### PR TITLE
Greeter orientation

### LINKED ISSUE #419: Allow greeter rotation
Allow the greeter to rotate and make it responsive so it will look good at any screen size.

### PR DESCRIPTION
**Pull request by capsia37**
This pull request enables greeter rotation and is based on #401 and #315 . 

It includes:
- rotation on mobile and on tablet
- rotation animations
- merge NarrowView and WideView in GreeterView
- CoverPage is now shown on desktop, mobile and tablet
- support for single and multi-user in all modes and devices
- change the position of clock and infographics depending on usage mode and orientation
- add support for delayed lockscreen on desktop
- add icons for multi-session support on mobile ( disabled by default because we only have one session type )

Possible future improvements:
We might want the CoverPage to show only when the user locked the account. When the device boots up for the first time or the user chooses to logout, the user would usually want to login again, so we should hide the CoverPage. When the device is locked after a certain time or the user decides to lock it, it should show the cover page.

Screenshots (on Nexus 5):
screenshot20210706_110421268
screenshot20210706_110414773
screenshot20210706_110410667
screenshot20210706_110401378

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This PR now conflicts on the `.gitignore` and `clickable.json` added by https://github.com/ubports/unity8/pull/398. Please update this PR to drop d8c48c4.

**Comment by Flohack74** [comment]
@capsia37 can you get this ready in lets say 2 weeks so we can include it in OTA-21?

**Comment by capsia37** [comment]
> @capsia37 can you get this ready in lets say 2 weeks so we can include it in OTA-21?

Sure, I'll do my best!

**Comment by Flohack74** [comment]
Also here friendly reminder, create an issue and link the PR to it :)

**Comment by capsia37** [comment]
Solves #419

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
